import { test, expect } from '@playwright/test';

test('token login, teams, tasks and mobile controls', async ({ page }) => {
  const base = process.env.HIVEMIND_TEST_UI_URL;
  await page.goto(base);
  await expect(page.getByText('Your projects.')).toBeVisible();
  await page.locator('#login-token').fill(process.env.HIVEMIND_TEST_TOKEN);
  await page.locator('#login-form button').click();
  await expect(page.locator('#page-title')).toHaveText('Overview');
  await expect(page.locator('#project-switcher')).toHaveValue('default');
  await page.getByRole('button', {name: 'Rooms', exact: true}).click();
  await page.locator('#room-create-form [name=name]').fill('release-review');
  await page.locator('#room-create-form [name=description]').fill('Coordinating the 1.5.0 release');
  await page.locator('#room-create-form button').click();
  await expect(page.locator('#room-list')).toContainText('release-review');
  await page.locator('#member-form [name=address_user]').fill('nikt');
  await page.locator('#member-form [name=address_device]').fill('macbook');
  await page.locator('#member-form [name=address_client]').fill('codex');
  await page.locator('#member-form button').click();
  await page.locator('#manager-form [name=address_user]').fill('nikt');
  await page.locator('#manager-form [name=address_device]').fill('macbook');
  await page.locator('#manager-form [name=address_client]').fill('codex');
  await page.locator('#manager-form button').click();
  await expect(page.locator('#room-list')).toContainText('Manager: nikt · macbook · codex');
  await page.getByRole('button', {name: 'Tasks', exact: true}).click();
  await page.locator('#task-create-form [name=title]').fill('Check release notes');
  await page.locator('#task-create-form [name=summary]').fill('Review documentation');
  await page.locator('#task-create-form button').click();
  await expect(page.locator('#task-list')).toContainText('Check release notes');
  await page.getByRole('button', {name: 'Instructions', exact: true}).click();
  await page.locator('#instruction-form [name=to_manager]').check();
  await page.locator('#instruction-form [name=body]').fill('Queue up the release reviews');
  await page.locator('#instruction-form button').click();
  await expect(page.locator('#instruction-list')).toContainText('Queue up the release reviews');
  await page.getByRole('button', {name: 'Agents', exact: true}).click();
  await expect(page.getByText('DMs are visible')).toBeVisible();
  await page.locator('#dm-form [name=address_user]').fill('nikt');
  await page.locator('#dm-form [name=address_device]').fill('macbook');
  await page.locator('#dm-form [name=address_client]').fill('codex');
  await page.locator('#dm-form [name=body]').fill('Ready for review');
  await page.locator('#dm-form button').click();
  await page.getByRole('button', {name: 'Messages', exact: true}).click();
  await page.locator('#message-channel').selectOption('dm');
  await expect(page.locator('#message-list')).toContainText('Ready for review');
  await page.setViewportSize({width: 390, height: 844});
  await expect(page.locator('#project-switcher')).toBeVisible();
  await expect(page.locator('#page-title')).toBeVisible();
  expect(await page.evaluate(() => localStorage.length)).toBe(0);
});

test('logout and second login cannot retain another private project task', async ({ page }) => {
  await page.goto(process.env.HIVEMIND_TEST_UI_URL);
  await page.locator('#login-token').fill(process.env.HIVEMIND_TEST_TOKEN);
  await page.locator('#login-form button').click();
  await expect(page.locator('#project-switcher')).toContainText('nikt.private');
  await page.locator('#project-switcher').selectOption('nikt.private');
  await page.getByRole('button', { name: 'Rooms', exact: true }).click();
  await page.locator('#room-create-form [name=name]').fill('private-review');
  await page.locator('#room-create-form [name=description]').fill('Nikt-only work');
  await page.locator('#room-create-form button').click();
  await page.getByRole('button', { name: 'Tasks', exact: true }).click();
  await page.locator('#task-create-form [name=title]').fill('A_ONLY_SECRET_TASK');
  await page.locator('#task-create-form [name=summary]').fill('Private details');
  await page.locator('#task-create-form button').click();
  await expect(page.locator('#task-list')).toContainText('A_ONLY_SECRET_TASK');
  await page.locator('#task-create-form [name=summary]').fill('PRIVATE_UNSENT_DRAFT');
  await page.locator('#instruction-form [name=body]').fill('PRIVATE_INSTRUCTION_DRAFT');
  await page.locator('#dm-form [name=body]').fill('PRIVATE_DM_DRAFT');
  await page.locator('#logout').click();
  await expect(page.locator('#login-screen')).toBeVisible();
  await page.locator('#login-token').fill(process.env.HIVEMIND_TEST_SECOND_TOKEN);
  await page.locator('#login-form button').click();
  await expect(page.locator('#project-switcher')).toHaveValue('ana.private');
  await expect(page.locator('#project-switcher')).not.toContainText('nikt.private');
  await page.getByRole('button', { name: 'Tasks', exact: true }).click();
  await expect(page.locator('#task-list')).not.toContainText('A_ONLY_SECRET_TASK');
  await expect(page.locator('#task-select')).not.toContainText('A_ONLY_SECRET_TASK');
  await expect(page.locator('#task-create-form [name=summary]')).toHaveValue('');
  await expect(page.locator('#instruction-form [name=body]')).toHaveValue('');
  await expect(page.locator('#dm-form [name=body]')).toHaveValue('');
});
